apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: gcr.io/vaulted-zodiac-236605/flask_api_server
        command: ["python", "/home/watchodogs_api_server/app.py"]
        ports:
        - containerPort: 5000