apiVersion: v1
kind: Service
metadata:
  name: apiloadbalancer
  labels:
    app: flask
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask
  type: LoadBalancer